### ISSUE TITLE
Move repo to github

### ISSUE THREAD

**Issue by ShahimEssaid** [owlcollab/owltools#111]
_From [cmung...@gmail.com](https://code.google.com/u/115850439786749293234/) on January 05, 2015 15:16:58_

\## SVN History

This should be straightforward to move over; Ignazio managed this for oboformat easily.

We would move everything across at first, but then may decide to split things up

\## Modularization

Lego stuff should go to a separate repo.

We should move OWLTools-Sim, but this will gradually be abandoned as owlsim-v3 (already a separate github repo) comes into play.

\## Issue Tracker

We will not attempt to migrate; we will start afresh with the gh tracker. We will leave the gcode one up and running and may manually migrate a select few items.

\## Wiki

There is a lot of good material on the wiki - will probably have to be manually moved, with links from old to new added.

_Original issue: http://code.google.com/p/owltools/issues/detail?id=111_

**Comment by ShahimEssaid** [comment]
_From [sha...@essaid.com](https://code.google.com/u/117011699684354642538/) on January 05, 2015 20:17:00_

Here is an example migration: https://github.com/ShahimEssaid/owltools I used git svn:

git svn clone --prefix=origin/ --authors-file=../authors --authors-prog=../authors-default  -s http://owltools.googlecode.com/svn .

I had to remove large files from the history because GitHub doesn't like > 50mb and refuses > 100mb files:

remote: error: GH001: Large files detected.
remote: error: Trace: 415df2b385d9bf1f9c72fa5a226558c6
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File OWLTools-Annotation/src/test/resources/rules/ontology/go.owl is 129.98 MB; this exceeds GitHub's file size limit of 100 MB
remote: error: File OWLTools-Core/src/test/resources/go.owl is 116.81 MB; this exceeds GitHub's file size limit of 100 MB
remote: error: File OWLTools-Annotation/src/test/resources/rules/ontology/go.owl is 129.54 MB; this exceeds GitHub's file size limit of 100 MB
remote: error: File OWLTools-Annotation/src/test/resources/rules/ontology/go.owl is 125.45 MB; this exceeds GitHub's file size limit of 100 MB

Ran the following to clear the history from these files:

git filter-branch --prune-empty -d /dev/shm/owltools \
  --index-filter "git rm --cached -f --ignore-unmatch OWLTools-Annotation/src/test/resources/rules/ontology/go.owl" \
  --tag-name-filter cat -- --all

git filter-branch --prune-empty -d /dev/shm/owltools \
  --index-filter "git rm --cached -f --ignore-unmatch OWLTools-Core/src/test/resources/go.owl" \
  --tag-name-filter cat -- --all

Maybe these files can be downloaded from somewhere else when tests are ran.

Finally:
git checkout -t -b hmc-clinic   
git remote add origin git@github.com:ShahimEssaid/owltools.git
git push -u origin master hmc-clinic

The current commits don't have proper user names but I can fix this once I have the correct user names and email addresses to use for the commits.

For the issues, I used: https://github.com/arthur-debert/google-code-issues-migrator For the wiki: https://github.com/trentm/googlecode2github

**Comment by ShahimEssaid** [comment]
_From [cmung...@gmail.com](https://code.google.com/u/115850439786749293234/) on January 05, 2015 21:41:34_

Fantastic. This would be a good time to refactor tests that involve enormous files

**Comment by ShahimEssaid** [comment]
_From [cmung...@gmail.com](https://code.google.com/u/115850439786749293234/) on January 06, 2015 09:10:01_

What about the generated apidocs? gh-pages?

**Comment by ShahimEssaid** [comment]
_From [cmung...@gmail.com](https://code.google.com/u/115850439786749293234/) on January 20, 2015 14:35:02_

After done, update GO FAQ and other links. Eg http://geneontology.org/faq/how-do-i-map-set-annotations-high-level-go-terms-go-slim

**Comment by ShahimEssaid** [comment]
_From [sha...@essaid.com](https://code.google.com/u/117011699684354642538/) on January 21, 2015 09:20:18_

Should we go ahead with this or not yet? 

Chris, I need the GitHub emails for you and Keiko (not the GitHub login/name) before running the final Git import. Can you please send them to me when we are ready for the move?

**Comment by ShahimEssaid** [comment]
_From [cmung...@gmail.com](https://code.google.com/u/115850439786749293234/) on January 21, 2015 11:09:21_

I just committed a few odds and ends to gcode.

We're ready to switch assuming this passes: http://build.berkeleybop.org/job/owltools/1160/ cjm AT berkeleybop.org

I think Heiko's will be hdietze AT lbl.gov

**Comment by ShahimEssaid** [comment]
_From [HDie...@lbl.gov](https://code.google.com/u/115902121950964170841/) on January 22, 2015 16:25:26_

I just removed all the big go.owl files from the test resources and replaced it smaller modules for the relevant tests. See r2446 for changes.

Does this mean you need to import the SVN again? Or is it just possible to pull the changes from SVN (even with the deleted go.owl files)?

**Comment by hdietze** [comment]
Done
