### ISSUE TITLE
Failure to Install Owltools using Maven

### ISSUE THREAD

**Issue by cedatorma** [owlcollab/owltools#119]
Hello, 

I'm currently attempting to install Owltools using maven 3.3.3 and JDK 1.8.0_45, but am having test failures. This install is being done in cygwin running on Windows 7.

Here is a summary of the error output:

mvn -X clean package
.....

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in owltools.util.TestTarjan

Results :

Tests in error:
  OWLGsonRendererTest.testOnt:65 ▒ OWLOntologyStorage Could not open file: /tmp/...

Any help would greatly be appreciated.

Ceda

**Comment by hdietze** [comment]
Thank you for reporting the problem.
At the moment, the test are not executed on Windows machine. The integration tests are currently only running on Linux based Jenkins machines.

The actual error is easily fixed though (change the hard-coded file path to proper a JUnit test folder). But there might be similar problems lurking in other tests.

As a work-around I would recommend to skip the tests in maven:
`mvn clean package -DskipTests`

If you want to speedup the process, you could also skip the source and javadoc:
`mvn clean package -DskipTests -Dmaven.javadoc.skip=true -Dsource.skip=true`

**Comment by cedatorma** [comment]
Thank you, maven has now built owl tools. However, I am encountering another problem when attempting to run the owltools wrapper script from the OWLTools-Runner/bin directory. 

Here is the output:

$ ./owltools
Error: Could not find or load main class owltools.cli.CommandLineInterface

Could this possibly due to differences in how cygwin handles paths?

**Comment by hdietze** [comment]
In theory, the script is cygwin aware. I'm currently creating a cygwin windows test installation.

Just to make sure the jar is valid, can you verify that the following command is working (in the OWLTools-Runner/bin folder):

`java -jar owltools-runner-all.jar --help`

This should print a list of all available owltools commands.

**Comment by hdietze** [comment]
Fixed the problematic cygwin detection in the owltools script.
The script has been tested with windows 7 and cygwin (32-bit version)

**Comment by hdietze** [comment]
Assuming the problem is fixed.
