### ISSUE TITLE
Put the auto-generated javadoc on gh-pages

### ISSUE THREAD

**Issue by cmungall** [owlcollab/owltools#122]
Such that they will be visible on http://owlcollab.github.com/owltools

@kltm has a standard sequence of commands for doing this in his npm makefiles - easy to transition this to maven targets?

Should do this as standard for all our java

**Comment by kltm** [comment]
I have a workflow I like, I can share that with @hdietze next time I see him.

**Comment by hdietze** [comment]
http://owlcollab.github.io/owltools/api/

**Comment by hdietze** [comment]
For convenience, there is now also an automatic redirect from  http://owlcollab.github.io/owltools to the Javadoc index page
