### ISSUE TITLE
map2slim does not map anything

### ISSUE THREAD

**Issue by koefoed** [owlcollab/owltools#124]
Hi,

I followed the installation instructions for [downloading the jars](https://github.com/owlcollab/owltools/wiki/Install-OWLTools#downloading-the-jar-and-script) (there is no version information; i tried 2 days ago, and again today), and tried the [map2slim example](https://github.com/owlcollab/owltools/wiki/Map2Slim) from the command line:

```sh
owltools http://purl.obolibrary.org/obo/go.obo --gaf http://geneontology.org/gene-associations/gene_association.goa_human.gz --map2slim --subset http://www.geneontology.org/ontology/subsets/goslim_generic.obo --write-gaf out.gaf
```
and
```sh
owltools http://purl.obolibrary.org/obo/go/go-basic.obo --gaf http://geneontology.org/gene-associations/gene_association.goa_human.gz --map2slim --subset http://www.geneontology.org/ontology/subsets/goslim_generic.obo --write-gaf out.gaf
```
but absolutely nothing is mapped:
```sh
2015-07-06 14:01:29,020 INFO  (ParserWrapper:67) Start loading ontology: http://purl.obolibrary.org/obo/go/go-basic.obo from: http://purl.obolibrary.org/obo/go/go-basic.obo
2015-07-06 14:02:25,306 INFO  (ParserWrapper:74) Finished loading ontology: http://purl.obolibrary.org/obo/go.owl from: http://purl.obolibrary.org/obo/go/go-basic.obo
2015-07-06 14:02:25,325 INFO  (GafCommandRunner:223) Start loading GAF from: http://geneontology.org/gene-associations/gene_association.goa_human.gz
2015-07-06 14:02:26,181 INFO  (GAFParser:290) Open stream as URL
2015-07-06 14:02:26,181 INFO  (GAFParser:302) Will decompress (.gz)
2015-07-06 14:02:38,586 INFO  (GafCommandRunner:234) Finished loading GAF.
2015-07-06 14:02:38,591 INFO  (GafCommandRunner:813) Creating subset map for: http://www.geneontology.org/ontology/subsets/goslim_generic.obo
2015-07-06 14:02:57,535 INFO  (GafCommandRunner:822) Input set: 43372
2015-07-06 14:02:57,535 INFO  (GafCommandRunner:823) Annotations: 483478
2015-07-06 14:02:57,535 INFO  (GafCommandRunner:829) iterating through all annotations
UNMAPPED: UniProtKB     A0A024QZ42      PDCD6           GO:0004198      GO_REF:0000033  IBA     PANTHER:PTN000021568    F       Programmed cell death protein 6 A0A024QZ42_HUMAN|PDCD6|hCG_1985580      protein taxon:9606      20140313        GO_Central                      
```
(cut lengthy output)
```sh
2015-07-06 14:03:22,922 INFO  (GafCommandRunner:852) # annotations mapped: 0
2015-07-06 14:03:22,922 INFO  (GafCommandRunner:853) # annotations in new set: 0
2015-07-06 14:03:22,922 INFO  (GafCommandRunner:854) avg mappings / ann: 0.0
2015-07-06 14:03:22,922 INFO  (GafCommandRunner:855) avg mappings / mapped ann: NaN
2015-07-06 14:03:22,923 INFO  (GafCommandRunner:856) # annotations unmapped: 483478
```

I have also tried two more [annotation](http://ftp.ebi.ac.uk/pub/databases/GO/goa/MOUSE/gene_association.goa_mouse.gz) [files](http://ftp.ebi.ac.uk/pub/databases/GO/goa/HUMAN/gene_association.goa_human.gz) from Uniprot but absolutely nothing is mapped.

The documentation is quite sparse and I cannot figure out what I am doing wrong -- can anyone help me?

**Comment by hdietze** [comment]
Hello,
thank you for contacting the owltools team. Yes, we agree that the documentation is sparse.

The --subset flag expects a single existing subset name (not a list or remote source). In case of GO (go-basic.obo) this could be one of the following: 
  * goslim_aspergillus
  * goslim_candida
  * goslim_chembl
  * goslim_generic
  * goslim_goa
  * goslim_metagenomics
  * goslim_pir
  * goslim_plant
  * goslim_pombe
  * goslim_synapse
  * goslim_virus
  * goslim_yeast
  * gosubset_prok

If you want to create a custom subset, please use `--idfile FILE` instead of `--subset`, where FILE is a file with the relevant identifiers for the custom set.

**Comment by koefoed** [comment]
Thank you very much, hdietze

So -- if I understand correctly -- the valid choices for the ```--subset``` flag are the ones defined in the ontology by lines starting with ```subsetdef:``` (near the beginning of the file).

Or if using the ```-idfile FILE``` option, the identifiers in the ```FILE``` are GO identifiers, for example ```GO:2000134``` (one on each line)

(I hope this can be useful to other people who may come across this page)

It would have been helpful to me if owltools had exited with an error when I gave it a wrong argument to ```--subset```.


What has me confused is that the Gene Ontology Consortium provides [some GO slims for download](http://geneontology.org/page/go-slim-and-subset-guide#GO_slims_available) and [states that](http://geneontology.org/page/go-slim-and-subset-guide#Map2Slim_option_in_OWLTools) 
>Given a GO slim file, and a current ontology (in one or more files), the Map2Slim script will map a gene association file (containing annotations to the full GO) to the terms in the GO slim

-- so I should give it both files? as in
```
owltools go-basic.obo goslim_generic.obo --gaf gene_association.goa_human.gz --map2slim --subset goslim_generic --write-gaf out.gaf
```
and since order matters, what difference does the order make?

The list of subsets you gave above is already available in the main ontology so what is the reason for the extra files?

**Comment by hdietze** [comment]
Yes each subset is declared in the OBO header, and in addition the actual assignment to a subset is done in the term stanza.

You only need the go-basic file (no merge required).
 * Merging the goslim_generic.obo would be redundant as go-basic contains all the required subset data.
 * Using only the goslim_generic.obo file would be wrong, as the map2slim requires the whole ontology to calculate the mapping (i.e. given a non slim term, find a the most specific parent term in the slim)

We will update the documentation on the GO main page, trying to make it less confusing.

The extra files for each subset are intended for other applications (e.g. enrichment tools). Some (3rd-party) tools were written without the support for subsets. So they use the prepared subset files instead.

**Comment by hdietze** [comment]
Also a quick comment about finding some build-version info for the JAR.
The `owltools-runner-all.jar` contains a manifest file (`META-INF/MANIFEST.MF`) with a build date entry: `owltools-build-timestamp`

**Comment by koefoed** [comment]
Thank you very much for your help and quick answer :-)

**Comment by caocaoxanh1987** [comment]
Dear Hdietze,

I hope this message finds you pretty well

I am trying to run map2slim on my own data using this command

owltools go.obo --gaf gene_association --map2slim --subset goslim_metagenomics.obo --write-gaf annotation.mapped.gaf 

the message I got: 
2017-08-14 15:42:52,984 WARN  (OBOFormatParser:1505) LINE: 478191 accepting bad xref with spaces:<MetaCyc:RXN-8282  has metacyc 2.4.1.67-RXN?>  LINE:
xref: MetaCyc:RXN-8282  has metacyc 2.4.1.67-RXN?
UNMAPPED: UniProtKB	Q8ZCW0	PHO4		GO:0016021	PMID:2676710	IMP		F			protein	taxon:9607	20090118	SGD			
UNMAPPED: UniProtKB	Q44006	PHO5		GO:0005737	PMID:2676711	IMP

output gaf file:
!gaf-version: 2.0
! This GAF has been mapped to a subset:
! Subset: goslim_metagenomics.obo
! Number of annotation in input set: 42024
! Number of annotations rewritten: 0

I have no idea with this problem. Could you please tell me what it is and how to deal with?

Thank you very much

**Comment by cmungall** [comment]
On 13 Aug 2017, at 23:32, caocaoxanh1987 wrote:

> Dear Hdietze,
>
> I hope this message finds you pretty well
>
> I am trying to run map2slim on my own data using this command
>
> owltools go.obo --gaf gene_association --map2slim --subset 
> goslim_metagenomics.obo --write-gaf annotation.mapped.gaf

Change

`--subset goslim_metagenomics.obo`

to

`--subset goslim_metagenomics`

The argument is the *name* of a subset already declared within the 
ontology


> the message I got:
> 2017-08-14 15:42:52,984 WARN  (OBOFormatParser:1505) LINE: 478191 
> accepting bad xref with spaces:<MetaCyc:RXN-8282  has metacyc 
> 2.4.1.67-RXN?>  LINE:
> xref: MetaCyc:RXN-8282  has metacyc 2.4.1.67-RXN?

You can ignore this warning

> UNMAPPED: 
> UniProtKB	Q8ZCW0	PHO4		GO:0016021	PMID:2676710	IMP		F			protein	taxon:9607	20090118	SGD			
> UNMAPPED: UniProtKB	Q44006	PHO5		GO:0005737	PMID:2676711	IMP
> output gaf file:
> !gaf-version: 2.0
> ! This GAF has been mapped to a subset:
> ! Subset: goslim_metagenomics.obo
> ! Number of annotation in input set: 42024
> ! Number of annotations rewritten: 0
>
> I have no idea with this problem. Could you please tell me what it is 
> and how to deal with?

This should be resolved with the correct subset arg. Apologies for the 
lack of clear error messages

**Comment by caocaoxanh1987** [comment]
Hi Cmungall,

Thank you very much for your quickly answer

After change the command line, I have still got the same problem. Nothing was mapped to the subset even I have change gene_association file and subset file.

gene_association to change was downloaded from: http://www.geneontology.org/gene-associations/
my gene_association file was: (I did not add anything in optional fields)

!gaf-version: 2.0 |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
UniProtKB | Q8ZCW0 | PHO4 |   | GO:0016021 | PMID:2676710 | IMP |   | F |   |   | protein | taxon:9607 | 20090118 | SGD
UniProtKB | Q44006 | PHO5 |   | GO:0005737 | PMID:2676711 | IMP |   | F |   |   | protein | taxon:9608 | 20090118 | SGD
UniProtKB | Q8XBY4 | PHO6 |   | GO:0016021 | PMID:2676712 | IMP |   | F |   |   | protein | taxon:9609 | 20090118 | SGD
UniProtKB | P32722 | PHO7 |   | GO:0045203 | PMID:2676713 | IMP |   | F |   |   | protein | taxon:9610 | 20090118 | SGD
UniProtKB | Q55434 | PHO8 |   | GO:0009883 | PMID:2676714 | IMP |   | F |   |   | protein | taxon:9611 | 20090118 | SGD
UniProtKB | C3KDE0 | PHO9 |   | GO:0008759 | PMID:2676715 | IMP |   | F |   |   | protein | taxon:9612 | 20090118 | SGD
UniProtKB | Q59692 | PHO10 |   | GO:0032153 | PMID:2676716 | IMP |   | F |   |   | protein | taxon:9613 | 20090118 | SGD
UniProtKB | P24125 | PHO11 |   | GO:0005524 | PMID:2676717 | IMP |   | F |   |   | protein | taxon:9614 | 20090118 | SGD
UniProtKB | P03766 | PHO12 |   | GO:0003824 | PMID:2676718 | IMP |   | F |   |   | protein | taxon:9615 | 20090118 | SGD
UniProtKB | Q9CKA6 | PHO13 |   | GO:0009982 | PMID:2676719 | IMP |   | F |   |   | protein | taxon:9616 | 20090118 | SGD

my command line:
owltools go.obo --gaf gene_association.gaf --map2slim --subset goslim_metagenomics --write-gaf annotation.mapped.gaf 

the output file were:
!gaf-version: 2.0
! This GAF has been mapped to a subset:
! Subset: goslim_metagenomics
! Number of annotation in input set: 3654
! Number of annotations rewritten: 0

and

!gaf-version: 2.0
! This GAF has been mapped to a subset:
! Subset: goslim_generic
! Number of annotation in input set: 3654
! Number of annotations rewritten: 0
, respectively

Do I need change anything else?

Thank you very much

Cheers
