### ISSUE TITLE
Be permissive in parsing qualifiers in GAFs, and report all appropriate warnings and errors

### ISSUE THREAD

**Issue by cmungall** [owlcollab/owltools#126]
RGD contains the following line:

> RGD     2291    Ccnb1   Contributes_to  GO:0035173      RGD:2316324|PMID:16141400       IDA             F       cyclin B1               gene    taxon:10116     20100208        RGD             

Formally this is invalid. The qualifier must be all lower case. What appears to be happening is that the qualifier is thrown out because it doesn't match the precise string 'contributes_to'. This would explain why the qualifier is not visible here: http://amigo.geneontology.org/amigo/gene_product/RGD:2291 (but check with @kltm).

Note there is no warning here:
http://build.berkeleybop.org/view/GAF/job/gaf-check-rgd/lastSuccessfulBuild/artifact/gaf-validation-summary.txt

 1. The GAF parser should be permissive and attempt to repair errors in reasonable ways: normalize to lowerCase, use underscores etc. Any repairs should be reported as warnings (yellow)
 2. If a qualifier is unrecognized even after repair it must generate an error (red)

Note: high priority as this example is in @pgaudet's chapter

**Comment by hdietze** [comment]
The owltools GAF (and GPAD) parser reports now unknown (error), repaired (warning), duplicate (warning) for the qualifier column.

For example rgd now produces parser warnings like this:
```
2369		WARNING	Repairing qualifier 'contributes_to' from: Contributes_to	
RGD	1303107	Vkorc1	Contributes_to	GO:0047057	RGD:1600457|PMID:15640149
```
