### ISSUE TITLE
Ecoloader has problems following 302 redirects

### ISSUE THREAD

**Issue by hdietze** [owlcollab/owltools#131]
As a result the ECO loader does have any valid mappings to GO evidence codes at the moment.

Potential issues:
 * ~~HTTP status codes (github, PURL?)~~
 * ~~potential bug in org.apache.commons.io.IOUtils~~

**Comment by hdietze** [comment]
tagging @cmungall @kltm as participant

**Comment by hdietze** [comment]
I have implemented a fix.
Turns out the switch from google code to github uncovered a limitation in the redirect handling.
We needed an explicit handler for redirects to a different protocol, i.e. `http` to `https`

**Comment by hdietze** [comment]
Tests are passing again on Jenkins, see job: https://build.berkeleybop.org/job/owltools/1279/

**Comment by stuartmiyasato** [comment]
It builds fine for me too.  Thanks for the quick fix!
