### ISSUE TITLE
Out of place URL in docs

### ISSUE THREAD

**Issue by kimrutherford** [owlcollab/owltools#141]
Hi.

In https://github.com/owlcollab/owltools/wiki/Install-OWLTools there is this text:

Change into the owltools directory and type the following:

```
https://github.com/owlcollab/owltools/issues/139
cd owltools/OWLTools-Parent
mvn clean install
```

Is the URL an accidental paste?

**Comment by hdietze** [comment]
Yes, that was a copy and paste error. It has been fixed. Thank you for reporting the issue.
