### ISSUE TITLE
Maven repository for OWLTools 0.3.0

### ISSUE THREAD

**Issue by IlincaTudose** [owlcollab/owltools#153]
Hi,

I've been using **OWLTools 0.3.0** in 2 projects. I was getting it from http://code.berkeleybop.org/maven/snapshot-repository/ and we were using it because it was compatible with the latest OWL API major release. 

The repository is not accessible any more. Can you recommend a repository? Is there any plan to push OWLTools to Maven Central?

Thanks,
ilinca.

**Comment by hdietze** [comment]
Thank you for reporting the error. 
Unfortunately the server which hosts `code.berkeleybop.org` has currently a hardware/software issue. We are hoping to restart the server in the next days.

**Comment by hdietze** [comment]
Good news the server has been fixed and the repositories are available again.

**Comment by cmungall** [comment]
Note that we're in the process of switching to mvncentral for dependencies so in future we should not be affect

Also, apologies for the disruption but the jar is available from our build server. Unfortunately this is only documented in the wiki, not the readme.... https://github.com/owlcollab/owltools/wiki/Install-OWLTools

**Comment by IlincaTudose** [comment]
Thanks, this is very good news indeed. It's very good to hear you're moving to mvncentral. What's the best way for me to keep up to date with the move?

**Comment by cmungall** [comment]
We have a mail list but it fell out of use

We could have one of the tickets be an 'announcement' ticket, and you 
could follow that (I assume you don't subscribe to the whole repo for 
notifications)

Either way I will be sure to email you of other major changes in future

**Comment by IlincaTudose** [comment]
I did add owltools to my watch list so I suppose I will get _some_ notifications. Thanks for the help.

**Comment by fbastian** [comment]
I'd like to be notified as well :)

**Comment by IlincaTudose** [comment]
Hi guys, the repository is down again. Should I open another ticket for it and when can we expect it to be up again?

**Comment by kltm** [comment]
Apologies--this is now up again. We were experiencing some software/hardware trouble, but have changed some settings to make the system more robust.
