### ISSUE TITLE
OWLTools-Runner should build a single executable file

### ISSUE THREAD

**Issue by dougli1sqrd** [owlcollab/owltools#173]
The OWLTools-Runner builds an executable jar for the owltools shell script. When tools or people need access to owltools, we also need to pass around the jar. The maven or make build should make a single executable file so we only need the one file to be passed around. 

We can do this by utilizing the fact that jars are in fact zips, and zips can be prepended with arbitrary data. So we can make the shell script owltools prepended to the executable jar and have the script execute itself.

This will improve portability.

**Comment by kltm** [comment]
As long as the versioning flags can be passed through for the self-report.

**Comment by dougli1sqrd** [comment]
What are the versioning flags for the self-report? Any command line args/options just get forwarded directly to the jar execution.

**Comment by kltm** [comment]
If they are all passed back, no issues at all.

**Comment by dougli1sqrd** [comment]
<img width="872" alt="screen shot 2017-02-28 at 5 32 06 pm" src="https://cloud.githubusercontent.com/assets/1422171/23437415/0e4e1f9e-fddc-11e6-9595-cd1ac1f930f9.png">
Like that?

**Comment by kltm** [comment]
That is correct. As we bundle the owlools jar into various projects for version locking and distribution, this feature has been critical in debugging.

**Comment by dougli1sqrd** [comment]
There are some hiccups with this at the moment. I'll be adding more commits with time.

**Comment by cmungall** [comment]
Shall we close this?

It looks like this is also fixed
https://build.berkeleybop.org/job/owltools/configure

so downstream consumers should be fine (many ontology travis jobs will try and grab an extra redundant jar, but this is harmless)

**Comment by kltm** [comment]
I still have access to the jars under target/, so I'm good there. I'll switch to the executable later on.
If we're going with actual tagged/branched versions and releases, it would be nice if that reported in the verion self-report.

**Comment by dougli1sqrd** [comment]
Yeah, we can probably close this. And yeah, I made sure the owltools job
was fixed.
