### ISSUE TITLE
owltools missing from OWLTools-Runner/bin !!!!

### ISSUE THREAD

**Issue by dosumis** [owlcollab/owltools#179]
I've just rebuilt OWLtools both locally and on VFB Jenkins.  The command line executable is missing from OWLTools-Runner/bin  in both cases.  

Multiple pipelines are broken by this as well as command line workflows I use.

@cmungall

**Comment by cmungall** [comment]
@dougli1sqrd - we need the mvn build to put the script in the usual place.

@dosumis - you can get it in OWLTools-Runner/target for now. The jar is now combined with the script

**Comment by dosumis** [comment]
> @dosumis <https://github.com/dosumis> - you can get it in OWLTools-Runner/target for now. The jar is now combined with the script
> 
Perfect.  Thanks.  Will it stay there?  (i.e. is it safe to change path spec in env on Jenkins server).

**Comment by dougli1sqrd** [comment]
I can do that, but it would be kinda kludgy. I think it would be better if we moved to having maven-built artifacts live in target/. It's closer to the maven party line that way and it makes the pom files more okay. Otherwise we're kinda making maven go uphill a little.

**Comment by dougli1sqrd** [comment]
This might not be as bad. I had tried to put it in the bin/ directory before but it was not very pretty. It looks like there's the copy-resources plugin. I'm giving that a shot.

**Comment by dougli1sqrd** [comment]
https://github.com/owlcollab/owltools/pull/180 Should fix it. But I think grabbing artifacts from target is still the way to go. At least now we won't be breaking anybody. Sorry about that.

**Comment by dougli1sqrd** [comment]
Can I close this issue?

**Comment by dosumis** [comment]
I just rebuilt OWLtools locally and there is no sign of the script:

ackee:owltools davidos$ ls OWLTools-Runner/bin/
owltools-runner-all.jar	owltools.script
ackee:owltools davidos$ OWLTools-Runner/bin/owltools.script 
Error: Could not find or load main class owltools.cli.CommandLineInterface

Not in  `OWLTools-Runner/target` either.

Judging from the builds on VFB Jenkins server, this was fixed at some point recently.

I'm very dependent on a functioning OWLtools so this is a serious pain.  

Note the doc still says: 

```md

## Running OWLTools (Unix and MacOS)

Running OWLTools requires a successful build, as described in the previous section.
 
+ OWLTools Command-Line Tools: The executables and the generated jar are both located in `OWLTools-Runner/bin`
```

**Comment by dougli1sqrd** [comment]
You're right, it doesn't seem to be copying the owltools executable back to the bin directory like we changed the build to do. 

I just cloned a fresh copy of owltools though, and after I built, there was a `owltools/OWLTools-Runner/target/owltools` executable.

I ran `mvn clean install -DskipTests`.

I thought we were copying that back into bin/, but it doesn't appear to be doing that. I'll look into that.

**Comment by dougli1sqrd** [comment]
So upon investigation, I'm noticing that `owltools` does seem to be copied correctly into `bin`. On my mac, it seems that you need to `chmod +x owltools` in order for it to be executable. You ought to be able to run `./owltools --help` and see the help message after `chmod`ing. Is this not happening for you? I'm running this off the latest master at the moment.

**Comment by dosumis** [comment]
I pulled the latest version yesterday and ran `mvn clean install` It passed all the tests. There's no owtools file to chmod in `OWLTools-Runner/bin/ ` or `owltools/OWLTools-Runner/target/`.

**Comment by dougli1sqrd** [comment]
Huh. That seems strange that we would have such different results from running the same command on the same code. 
So I ran git log, here's what I get:
```
edouglass@Erics-MacBook-Pro:~/code/owltools[master]$ git log -1
commit 3390e26f26e570a12f6e116cc98fe5c03cb15e1d
Merge: d85287c 5aabc3d
Author: kltm <github.com@genkisugi.net>
Date:   Fri Mar 31 14:02:16 2017 -0700

    Merge pull request #178 from owlcollab/amigo-290

    Created a method that returns an OboGraph JSON string for any class or object prop
```

Also, make sure you're on the master branch. This is my git status:
```
edouglass@Erics-MacBook-Pro:~/code/owltools[master]$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
```

I'm running java 8:
```
edouglass@Erics-MacBook-Pro:~/code/owltools[master]$ java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

And maven 3.3.9:
```
edouglass@Erics-MacBook-Pro:~/code/owltools[master]$ mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T08:41:47-08:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.5", arch: "x86_64", family: "mac"
```

Can you verify that your `OWLTools-Runner/pom.xml` has the "maven-resources-plugin" with the "copy-resources" goal, around lines 103 and 110 respectively:
```
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-resources-plugin</artifactId>
	<version>3.0.2</version>
	<executions>
		<execution>
			<id>copy-owltools</id>
			<phase>verify</phase>
			<goals>
				<goal>copy-resources</goal>
			</goals>
...
</plugin>
```

And that you have the "really-executable-jar" plugin around line 85:
```
<plugin>
        <groupId>org.skife.maven</groupId>
        <artifactId>really-executable-jar-maven-plugin</artifactId>
	<version>1.4.1</version>
...
</plugin>
```

Lastly, can I see output of ls -l in your OWLTools-Runner/target/ directory?
```
edouglass@Erics-MacBook-Pro:~/code/owltools/OWLTools-Runner/target[master]$ ls -l
total 142120
-rw-r--r--  1 edouglass  staff    124202 Apr  3 14:25 OWLTools-Runner-0.3.0-SNAPSHOT-javadoc.jar
-rw-r--r--  1 edouglass  staff    107624 Apr  3 14:25 OWLTools-Runner-0.3.0-SNAPSHOT-sources.jar
-rw-r--r--  1 edouglass  staff   2323275 Apr  3 14:25 OWLTools-Runner-0.3.0-SNAPSHOT-tests.jar
-rw-r--r--  1 edouglass  staff  34993864 Apr  3 14:25 OWLTools-Runner-0.3.0-SNAPSHOT.jar
drwxr-xr-x  3 edouglass  staff       578 Apr  3 14:25 apidocs
drwxr-xr-x  3 edouglass  staff       170 Apr  3 14:25 classes
drwxr-xr-x  3 edouglass  staff       102 Apr  3 14:25 generated-sources
drwxr-xr-x  3 edouglass  staff       102 Apr  3 14:25 generated-test-sources
drwxr-xr-x  2 edouglass  staff       136 Apr  3 14:25 javadoc-bundle-options
drwxr-xr-x  2 edouglass  staff       102 Apr  3 14:25 maven-archiver
drwxr-xr-x  3 edouglass  staff       102 Apr  3 14:25 maven-status
-rw-r--r--  1 edouglass  staff    208296 Apr  3 14:25 original-OWLTools-Runner-0.3.0-SNAPSHOT.jar
-rwxr-xr-x  1 edouglass  staff  34994536 Apr  3 14:25 owltools
drwxr-xr-x  6 edouglass  staff      1496 Apr  3 14:25 test-classes
```

Can you tell me anything else about your environment? Are you running this on jenkins? Local laptop machine? 

Thanks! Sorry this messing you up!

**Comment by dougli1sqrd** [comment]
@dosumis did you end up getting this to work for you?

**Comment by dosumis** [comment]
Trying a clean install now.  Will let you know.

**Comment by dosumis** [comment]
Clean install works to => and owltools script.

One other slightly irritating change.   Also had to switch jar

owltools/OWLTools-Runner/bin/owltools-runner-all.jar

>

OWLTools-Runner/target/OWLTools-Runner-0.3.0-SNAPSHOT.jar

This seems to work, but I had to guess that it would (does 'all' have more content? if so what?).  Also means I'll have to change paths when version changes).  I can see that this is more like standard behavior, but would be nice to have a heads up of changes like this in future.

(BTW - I'm not using maven in this case as found it a bit of a pain to get working with Jython.  Not planning to investigate this further as I'm gradually dropping Jython in favor of Scala.)
