### ISSUE TITLE
Owltools generating spurious output on extract

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [owlcollab/owltools#219]
I'm using owltools (and trying robot too but it behaves the same way) to do an extraction, and it works on a simpler import owl file, but it is generating spurious output for the larger merged ontology file (also generated by robot) that includes the import.  I'm pretty sure the merged ontology file has some OWL referential loop structure or syntax error that owlapi can't navigate, and so owlapi is cutting its parse short, and returning its parse (possibly with some erronious extraction), but without any error indication. 

So is there an OWL validation tool that will reliably determine what owlapi can parse successfully?

Thanks

**Comment by cmungall** [comment]
hmm, may have more luck on robot tracker or even owlapi if you can replicate at that level - specific example would help

**Comment by Public-Health-Bioinformatics** [comment]
Ok, I'll circle back to this later; found that ontofox does great job getting items and context.
