### ISSUE TITLE
Current master build tests fail (commit a69a05a3002c444dc8625c704d936b52a23e47b6)

### ISSUE THREAD

**Issue by RichardBruskiewich** [owlcollab/owltools#270]
See error trace below, resulting from '_mvn clean install_' of the master branch, (commit a69a05a3002c444dc8625c704d936b52a23e47b6)

I'm thinking that owltools is a huge project. I know that it is important to get the semantics right and the tool working, but having a usable tool along the way is important too.  I can imagine there being alot of code to fix to get tests working but that large parts of the system might still be useable.   

Would it make sense to keep the "master" or "release" build working with (documented) disabled JUnit tests and mainly keep the tests activated in a 'develop' branch, or suggest that developers only enable those tests upon which they work (plus, of course, all the "working" tests from the past... running  in case their code "breaks" something)?

That would make for a more sane situation. "Iffy" classes or API's in the code base could also be documented with. caveats as "experimental" in the master branch until they. are fully tested as "release candidates".

In other words, make the project continually usable to end users who wish to deploy it (e,g, in the NCATS Translator workflows) even as the system is being improved? 

I'm disabling the failing tests (noted. below) in my local building the hope of getting to some kind of useable JAR. I realize that the resulting application will have (semantic) deficiencies in some result or another, but I have to imagine that something sensible and helpful result might still come out of the application (if the code. runs!) to allow the work using the code to continue.

========================================================================

Master, commit a69a05a3002c444dc8625c704d936b52a23e47b6

Failed tests: 
  CheckPotentialRedundantRelationsTest.test1:29 expected:<[part_of]> but was:<[BFO:0000050]>
  CheckPotentialRedundantRelationsTest.test2:48 expected:<[part_of]> but was:<[BFO:0000050]>
  TBoxUnFoldingToolTest.testUnfold:35 expected:<...bjectSomeValuesFrom([regulates 'regulates' ObjectIntersectionOf(GO:0008283 'cell proliferation' ObjectSomeValuesFrom(part_of] 'part_of' GO:000182...> but was:<...bjectSomeValuesFrom([RO:0002211 'regulates' ObjectIntersectionOf(GO:0008283 'cell proliferation' ObjectSomeValuesFrom(BFO:0000050] 'part_of' GO:000182...>
  OWLGraphWrapperEdgesAdvancedTest.testGetNeighbors:163 null
  OWLGraphWrapperEdgesAdvancedTest.testPull177:207 null
  RetrieveRelationByLabelTest.getRelationById:44 expected:<[part_of]> but was:<[BFO:0000050]>
Tests in error: 
  OWLGraphWrapperEdgesExtendedTest.shouldCombinePropertyPairOverSuperProperties:254 » Runtime
  OWLGraphWrapperEdgesExtendedTest.shouldGetSubPropertiesOf:98 » Runtime Multipl...
  OWLGraphWrapperEdgesExtendedTest.shouldGetSubPropertyClosureOf:115 » Runtime M...
  OWLGraphWrapperEdgesExtendedTest.shouldGetSubPropertyReflexiveClosureOf:137 » Runtime
  OWLGraphWrapperEdgesExtendedTest.shouldGetSuperPropertyReflexiveClosureOf:160 » Runtime

Tests run: 162, Failures: 6, Errors: 5, Skipped: 5

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] OWLTools-Parent 0.3.0-SNAPSHOT ..................... SUCCESS [  0.942 s]
[INFO] OWLTools-Core 0.3.0-SNAPSHOT ....................... FAILURE [02:07 min]
[INFO] OWLTools-Annotation 0.3.0-SNAPSHOT ................. SKIPPED
[INFO] OWLTools-Oort 0.3.0-SNAPSHOT ....................... SKIPPED
[INFO] OWLTools-Sim 0.3.0-SNAPSHOT ........................ SKIPPED
[INFO] OWLTools-Web 0.3.0-SNAPSHOT ........................ SKIPPED
[INFO] Lego 0.0.3-SNAPSHOT ................................ SKIPPED
[INFO] OWLTools-Solr 0.3.0-SNAPSHOT ....................... SKIPPED
[INFO] OWLTools-Runner 0.3.0-SNAPSHOT ..................... SKIPPED
[INFO] OWLTools-NCBI 0.3.0-SNAPSHOT ....................... SKIPPED
[INFO] Golr-Client 0.3.0-SNAPSHOT ......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

=========================================================================

**Comment by balhoff** [comment]
Looks like all relate to property shorthand names vs. CURIEs. Maybe something changed in a dependency? I can look at it but not sure how soon.
