### ISSUE TITLE
Error: owltools.cli.CommandLineInterface

### ISSUE THREAD

**Issue by pbuttigieg** [owlcollab/owltools#277]
Hi all,

Strange error popping up after I updated owltools to the latest release or the current repo state.

```
Could not find or load main class owltools.cli.CommandLineInterface
```

I tried downloading the JAR and building it locally.
I'm running it on CygWin for Windows, which does a pretty good job of emulating a UNIX environment. 

Ever seen anything like that?

**Comment by cmungall** [comment]
Did you download from the jenkins build?

Can you check you have the bundled jar+script, should look like this:

```
$ du -sh owltools
 37M    owltools
```

also try 
```
which owltools
```

to make sure you are using the one you think you are using

**Comment by pbuttigieg** [comment]
Yes, this all checks out. It's the owltools I just built from the repo yesterday, both the .script and the JAR are in my PATH.

**Comment by matentzn** [comment]
> I updated Java yesterday too and that seems to check out.

Did the error happen also before that? There is a small possibility that the java version owltools was build with is not compatible with the one you are running. Or at least this is something my brain seems to associate with when seeing the sentence `Could not find or load main class owltools.cli.CommandLineInterface`.

Would using docker be a possibility for you? You could use the owltools [embedded](https://hub.docker.com/r/obolibrary/odkfull) in the ODK..

**Comment by pbuttigieg** [comment]
>Did the error happen also before that? There is a small possibility that the java version owltools was build with is not compatible with the one you are running. Or at least this is something my brain seems to associate with when seeing the sentence Could not find or load main class owltools.cli.CommandLineInterface.

Yes, same error before the Java update, after I updated owltools. My feeling is that the error is in the Java direction too. 

> Would (in the meantime) using docker be a possibility for you? You could use the owltools embedded in the ODK.. 

I'm trying to get docker up on Windows 7, but it's not complying. Will keep at it, but would like to see if this owltools issue can be resolved.

**Comment by pbuttigieg** [comment]
docker seems to be in my path and `docker run --help` produces the expected output, but is seems that the daemon isn't running. I've tried a bunch of advise in dark forums, but no avail. Any advice would be much appreciated.

**Comment by matentzn** [comment]
If you are using windows 7 home, i.e. not professional, you will have installed the docker toolbox.. That is a bit different from normal docker community edition. Unfortunately I do not know exactly how to use this :( Sorry.

@balhoff Do you have any idea how to help regarding the original issue?

**Comment by pbuttigieg** [comment]
The forums are all over the place with recommendations. I'm on Win 7 professional, but still seem to need the Toolbox. Thanks for the attempt. 

Refocusing, is there anyway to kill the owltools error? What version of Java is "standard"?

**Comment by matentzn** [comment]
@pbuttigieg Unfortunately I have nothing today with owltools so I cant help much. Lets see what @balhoff and @cmungall  suggest. If you do have jdk installed, you could try clone this repo and mvn install the java file as per instruction on the README. Just a guess though. Java 8 is, unfortunately, still what passes for standard around ontology tools in my experience.

**Comment by balhoff** [comment]
@pbuttigieg do you know what version of Java you are using? As @matentzn says, we are mostly still testing and running on Java 8. But if that is the issue then it might not be that hard to make it function correctly on later versions. But I guess we don't know right now that this is the problem.

**Comment by balhoff** [comment]
I added a Travis config to test on JDK 11, seems to work fine: https://github.com/owlcollab/owltools/pull/278

**Comment by pbuttigieg** [comment]
Thanks for the attempt all, this must be some sort of machine-specific thing. Closing this for now. If I figure it out (rather than just switching machines) I'll post here.

**Comment by cmungall** [comment]
Note that also we aim to remove all owltools deps from the envo build
process, obviating this issue..
