### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by dougli1sqrd** [owlcollab/owltools#288]
Should I produce a new release?

**Comment by balhoff** [comment]
I think so, yes. Please update the version in the pom and tag.

**Comment by cmungall** [comment]
I don't have any context for this question, but it should be ok to go ahead.

I don't know when the last release, which will be the one golr loading is using. Would be a good idea to check if it has been a long time, as owlapi will be upgraded etc

**Comment by kltm** [comment]
I'm also out of the loop here (and get nervous around things like this).
AmiGO/GOlr currently use a version embedded in a Docker image, with the rest of the pipeline using one that it built itself, so there should no direct pipeline consequences if compatible.

**Comment by matentzn** [comment]
Is there any chance we can get a volunteer to implement this first?
https://github.com/owlcollab/owltools/issues/289

We relatively urgently need this for exomiser.. (right, @julesjacobsen ?)

**Comment by dougli1sqrd** [comment]
In forming documentation for the pipeline, I realized that in Jenkins and for me personally when I run the Makefile in go-site, we use a live built owltools. Meaning we build owltools right then, and use the built binary from there. But the documentation on owltools states to use the released version on github. However we haven't released a new version in something like at least a year. The instructions also say you can get owltools from the old Jenkins, which is not great advice.

**Comment by julesjacobsen** [comment]
It's not super-urgent, but this is definitely needed for pheval.

**Comment by balhoff** [comment]
We still need a release—and we should start doing this regularly.

**Comment by dougli1sqrd** [comment]
Okay, I can get on this.

**Comment by matentzn** [comment]
Where is the latest release located now? Some of my Travis pipelines are failing now because bbop servers [are gone](https://github.com/INCATools/ontology-development-kit/issues/332)..

Is this 4 year old GitHub release still the most up to date release, or have we simply not been keeping up with GitHub releases over the years?

**Comment by kltm** [comment]
@matentzn, It is the latter. @dougli1sqrd is looking at getting a new release out. In the interim, the stable-but-hacky location is that of a GO release https://github.com/INCATools/ontology-development-kit/issues/332#issuecomment-604777077 .

**Comment by matentzn** [comment]
Cheers @kltm :P Just want to avoid to hard-code the GO release URLs into the ODK build process now. I will wait for @dougli1sqrd then! :) Thanks.

**Comment by dougli1sqrd** [comment]
https://github.com/owlcollab/owltools/releases/tag/2020-04-06

**Comment by matentzn** [comment]
Copy of my comment over at ODK: the Berkley build gave us:
http://build.berkeleybop.org/userContent/owltools/owltools http://build.berkeleybop.org/userContent/owltools/ontology-release-runner
http://build.berkeleybop.org/userContent/owltools/owltools-oort-all.jar

Can those be added to the release as well @dougli1sqrd ?

Thanks!

**Comment by balhoff** [comment]
@dougli1sqrd @matentzn I added some additional files to the release at https://github.com/owlcollab/owltools/releases/tag/2020-04-06 from Eric's tag. Does that cover what people have been using?
