### ISSUE TITLE
Getting 500 error

### ISSUE THREAD

**Issue by callahantiff** [owlcollab/owltools#293]
Trying to `wget` from `http://build.berkeleybop.org/userContent/owltools/owltools` and getting the following error:

```bash
Resolving build.berkeleybop.org (build.berkeleybop.org)... 131.243.192.185
Connecting to build.berkeleybop.org (build.berkeleybop.org)|131.243.192.185|:80... connected.
HTTP request sent, awaiting response... 500 Server Error
2020-04-25 03:02:12 ERROR 500: Server Error.
```

**Comment by balhoff** [comment]
That server is out of commission now. We put a pre-built release here on github as a replacement: https://github.com/owlcollab/owltools/releases/tag/2020-04-06

**Comment by callahantiff** [comment]
> That server is out of commission now. We put a pre-built release here on github as a replacement: https://github.com/owlcollab/owltools/releases/tag/2020-04-06

Thanks @balhoff!
