### ISSUE TITLE
Download error from "Install OWLTools" wiki page

### ISSUE THREAD

**Issue by kimrutherford** [owlcollab/owltools#301]
Hi.

The "Download owltools" link on this page: https://github.com/owlcollab/owltools/wiki/Install-OWLTools

Returns this error:

```
com.thoughtworks.xstream.mapper.CannotResolveClassException: hudson.security.GlobalMatrixAuthorizationStrategy
```

**Comment by balhoff** [comment]
Thanks! Looks like the wiki needs to be updated. The old server is gone, and we have put release files in a much better place (here!): https://github.com/owlcollab/owltools/releases
