### ISSUE TITLE
Server in test no longer available

### ISSUE THREAD

**Issue by balhoff** [owlcollab/owltools#326]
@kltm these tests no longer pass, since this server is offline. Any replacement?

https://github.com/owlcollab/owltools/blob/9faa4f42b761839a26e8c8096cd24044e2bdcfc7/Golr-Client/src/test/java/org/bbop/golr/java/RetrieveGolrAnnotationsTest.java#L72

**Comment by kltm** [comment]
@balhoff Huh, well...
Assuming the tests are "mild", one could probably just go for: "https://golr.geneontology.org/solr". This is the production server, so if this is going to cause sweat, let's figure something else out. (The most "correct" solution here would be to spin up a local docker image with a grab of a known version of the solr index, but that is unlikely to work easily in GHA.)
